stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: evertonaulian/node:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: index.docker.io
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: evertonaulian/node
      pushRemote: true
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    env:
      VERSION: ${CICD_GIT_COMMIT}
timeout: 60
notification:
  recipients:
  - recipient: '#rancher'
    notifier: c-trw7c:n-l2z7l
  condition:
  - Success
