stages:
- name: Build and Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: evertonaulian/node
      pushRemote: true
      registry: 127.0.0.1:34070
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: '#rancher'
    notifier: c-trw7c:n-l2z7l
  condition:
  - Success
