apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: node
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node
  labels:
    app: node
spec:
  selector:
    app: node
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node
        tier: frontend
    spec:
      containers:
      - image: evertonaulian/node
        name: node
        ports:
        - containerPort: 3000
          name: node
          